
source 'https://gems.ruby-china.com/'


gem 'jekyll', '3.8.4'
gem 'tzinfo', '2.0.1'
gem 'tzinfo-data'
gem 'sass'
group :jekyll_plugins do
  gem 'jekyll-feed', '0.11.0'
  gem 'jekyll-seo-tag', '2.5.0'
  gem 'jekyll-sitemap', '1.2.0'
end
